name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"  # match your pyproject.toml requires-python

      - name: Install uv
        run: pip install uv

      - name: Install project dependencies
        run: uv sync --all-extras --dev

      - name: Ruff Lint
        run: uv run ruff check .

      - name: Ruff Format (check-only)
        run: uv run ruff format --check .

      - name: Black (check-only)
        run: uv run black --check .

      - name: Mypy
        run: uv run mypy .
